// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Só a CLI lê daqui — o app conecta pelo adapter em src/lib/prisma.ts.
    // Migration precisa de conexão em modo sessão: o transaction pooler do
    // Supabase (:6543, pgbouncer) não sustenta o advisory lock e a CLI trava.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
